### ISSUE TITLE
ServerError: Lua: Runtime error from mod 'stamina' in callback on_joinplayer()

### ISSUE THREAD

**Issue by diogogomes** [minetest-mods/stamina#15]
Minetest not run when mod **stamina** is selected.

**Minetest:** 0.4.15
**Stamina:** unversioned (master)

**Debug Log**
`ERROR[Main]: ServerError: Lua: Runtime error from mod 'stamina' in callback on_joinplayer(): /home/user/.minetest/mods/stamina/init.lua:29: attempt to call method 'get_attribute' (a nil value)`
`ERROR[Main]: stack traceback:`
`ERROR[Main]: /home/user/.minetest/mods/stamina/init.lua:29: in function 'get_int_attribute'`
`ERROR[Main]: /home/user/.minetest/mods/stamina/init.lua:345: in function </home/user/.minetest/mods/stamina/init.lua:343>`
`ERROR[Main]: /usr/share/minetest/builtin/game/register.lua:412: in function </usr/share/minetest/builtin/game/register.lua:392>`

**Comment by sofar** [comment]
Not a bug. Staminas latest versions require a dev build of minetest.

**Comment by sofar** [comment]
Try using the 0.4.15 tagged commit:

https://github.com/minetest-mods/stamina/archive/0.4.15.zip

**Comment by diogogomes** [comment]
Sorry, I miss that tag because I have installed with bower.

If you don't mind, I'll commit a bower.json.
