### ISSUE TITLE
ERROR '<eof>' expected near 'end' (Stamina 0.4.15)

### ISSUE THREAD

**Issue by diogogomes** [minetest-mods/stamina#17]
I have installed 0.4.15 version and Minetest not start when stamina are selected:

`ERROR[Main]: ModError: Failed to load and run script from /home/username/.minetest/mods/stamina/init.lua:`
`ERROR[Main]: /home/username/.minetest/mods/stamina/init.lua:137: '<eof>' expected near 'end'`

**Comment by sofar** [comment]
This was fixed with 43dd5438f7fc1833ef95388413081f065cbd736a
