### ISSUE TITLE
Background not work

### ISSUE THREAD

**Issue by MoNTE48** [minetest-mods/stamina#2]
background = "stamina_hud_bg.png" not working. Minetest API it does not support

**Comment by MoNTE48** [comment]
Poor fix :(

**Comment by sofar** [comment]
I don't intend to replace BlockMen's HUD/hunger mod, this code was just not removed when I forked the code. This mod is meant to stay as is for now, without a background hud.

**Comment by 0-afflatus** [comment]
I'm more than happy with the way it looks FWIW.
