### ISSUE TITLE
Using node breakers with masq causes player who placed it to starve

### ISSUE THREAD

**Issue by mtango688** [minetest-mods/stamina#9]
Pipeworks machines somehow cause you to starve, and that is hunger/stamina's fault. Or so I've been told.

See https://github.com/minetest-mods/pipeworks/issues/146

**Comment by tenplus1** [comment]
This issue can be closed now, no ?

**Comment by mtango688** [comment]
Oh... Yeah, this should be working. I can't confirm because I've long since "fixed" it by changing certain parameters. But, yeah.

**Comment by sofar** [comment]
We can reopen if someone spots it again, but I think it's fixed properly.
